README.md

Fixes the path to the microsoft.list sources file in the README.

Fix path to sources file in README

---

README.md

Fix for a small mistake I found while reading the read me.

Fix a typo in README (with -> will)

---

src/ProcDumpConfiguration.c

Rename variable sigset -> sig_set to avoid conflict w/function sigset

---

include/ProcDumpConfiguration.h
src/CoreDumpWriter.c
src/Logging.c
src/ProcDumpConfiguration.c

Fix complaints from cppcheck, valgrind and remove some unused code.

Misc cleanups

---

include/ProcDumpConfiguration.h
src/CoreDumpWriter.c
src/ProcDumpConfiguration.c

Added error-reaction in WriteCoreDumpInternal() according to null process name.

Added error-checking against null process name in sanitize().

---

docs/coreclrintegration.md

Short doc on the why and how of procdump .net core integration.

procdump and .net core integration doc

---

INSTALL.md

Changes include:
- added support for Ubuntu 19.10
- removed EOL openSUSE 42.3
- added support for RHEL 8

Updated Install Docs

---

Makefile
azure-pipelines.yml
dist/procdump.spec.in

Fixes in package naming to use AZDO build ID.

1.1 build fix

---

CONTRIBUTING.md
INSTALL.md

Changes Include;
- Updated installation documentation to include Ubuntu 20.04 in anticipation of its release on 4/23

Ubuntu 20.04 Documentation Update

---

INSTALL.md
README.md
src/ProcDumpConfiguration.c

Changes Include:
- Fixes #90 
- Updates to install documentation to remove EOL distros and add new ones

Fixed spelling in README and spacing in usage prompt

---

INSTALL.md

removing EOL 19.10

---

README.md

Updating build badges to new CI pipeline

---

include/Logging.h
include/ProcDumpConfiguration.h
src/Logging.c
src/ProcDumpConfiguration.c
src/Procdump.c
src/TriggerThreadProcs.c

The errors are the same with #101 .
The environment I'm using is Debian testing with kernel 5.8.0-2-amd64
gcc (Debian 10.2.0-13) 10.2.0
Besides, I can signed the CLA. How can I send the CLA to microsoft?
There is no information about how to send the signed CLA on this page:
https://cla.opensource.microsoft.com/

Fix multiple definition in compiling

---

INSTALL.md

Reverts Sysinternals/ProcDump-for-Linux#125

Revert "Procdumo 1.2 install update"

---

include/ProcDumpConfiguration.h
src/ProcDumpConfiguration.c
src/Process.c
src/TriggerThreadProcs.c

Also fixes: 122 - https://github.com/Sysinternals/ProcDump-for-Linux/issues/122

Fix:135-Specify multiple CPU usage condition is not working

---

azure-pipelines.yml

The ProcDump_Run_Unit_Tests job synced to master rather than source of PR.

Remove sync to master

---

.devcontainer/Dockerfile_Rocky
.devcontainer/Dockerfile_Ubuntu
.devcontainer/devcontainer.json

Add VSCode dev container support

Add VSCode dev container support

---

ebpf/procdump_ebpf.c
src/ProcDumpConfiguration.cpp

Add mmap/munmap to resource tracking (#230). Fix gc generation configuration printout (#229)

---

src/CoreDumpWriter.cpp

fixes https://github.com/microsoft/ProcDump-for-Linux/issues/77

fix infinite loop when gcore is not installed

---

CMakeLists.txt
fix_skeleton.sh

Temporary fix for bpf code generation to work across compiler tool chain

Temporary fix for bpf code generation to work across compiler tool chain
