src/ProcDumpConfiguration.c

< and != have higher operator precedence than =
Signed-off-by: Michael Sartain <mikesart@fastmail.com>

Add parentheses around assignments in conditionals

---

src/Procdump.c

typo Procdump.c

---

Makefile
README.md
include/ProcDumpConfiguration.h
src/ProcDumpConfiguration.c
src/Procdump.c
tests/integration/ProcDumpTestApplication.c
tests/integration/runProcDumpAndValidate.sh
tests/integration/scenarios/high_cpu_by_name.sh
tests/integration/scenarios/low_cpu_by_name.sh

This change implements the '-w' command line parameter to
allow waiting for a specific process name to launch as
proposed in #19.
This is done by looping over the `/proc/` filesystem and
comparing the names as returned by `GetProcessName` to the
name passed on the command line.
`GetProcessName` prints error messages if an error occurs -
as we're calling it a lot in `WaitForProcessName` instead of
once before, I added a new parameter to allow suppressing
the error messages while looping over `/proc/`.
Tests are done by running a small helper application 
which either sleeps or runs an endless loop for 5 seconds
and using the high/low CPU load triggers in combination
with `-w`.

Implement waiting for process by name (-w parameter)

---

procdump.1

The new -w parameter was documented in the output of
`procdump -h` and in the README.md file but I forgot to add
it to the manual page.

Document -w parameter in manpage (fix for #34)

---

Makefile
azure-pipelines.yml

Changes Include:
- Fixed auto-versioning for non AZDO builds & how BuildId is passed into debbuild/rpmbuild

Auto-Versioning Fix

---

tests/integration/runProcDumpAndValidate.sh

The Debian executable `stress-ng` is build with the options `HAVE_BSD_UNISTD_H` and `HAVE_SETPROCTITLE`. Those options
enables setting the process name to the stressor name.
Related `makeconfig` checks are
```
make -f Makefile.config --no-print-directory HAVE_CONFIG=1 HEADER=bsd/unistd.h have_header_h
make -f Makefile.config --no-print-directory HAVE_CONFIG=1 TEST_LIBS=-lbsd TEST_PROG=test-setproctitle have_test_prog
```
This change was introduced in `stress-ng` release V0.10.13 (see commit [#f224f5db5](https://kernel.ubuntu.com/git/cking/stress-ng.git/commit/?id=f224f5db5)).
Hence for example for the execution of `stress-ng -c 1 -l 20 --timeout 20s -q` the process names reported by `ps` are different
**stress-ng before V0.10.13**
```
stress-ng -c 1 -l 20 --timeout 20s -q
stress-ng -c 1 …
```

Fix to get child process PID's regardless of their process name.

---

src/ProcDumpConfiguration.c

As reported in #92, parsing the command line parameters can currently lead to a crash in `getopt_long`. This is caused by a missing terminating entry in the `long_options` array which is required as described in the man page for getopt_long [1].  Without this entry, getopt_long continues to parse garbage values on the stack as options.
Adding the missing entry fixes the crash.
[1]: `The last element of the array has to be filled with zeros.`
Fixes: #92

ProcDumpConfiguration: fix crash in getopt_long

---

README.md
include/ProcDumpConfiguration.h
procdump.1
src/CoreDumpWriter.c
src/ProcDumpConfiguration.c
tests/integration/runProcDumpAndValidate.sh
tests/integration/scenarios/high_cpu.sh
tests/integration/scenarios/high_cpu_by_name.sh
tests/integration/scenarios/high_cpu_custom_core_file_name.sh
tests/integration/scenarios/high_cpu_nonexisting_output_directory.sh
tests/integration/scenarios/high_cpu_notdump.sh
tests/integration/scenarios/low_cpu.sh
tests/integration/scenarios/low_cpu_by_name.sh
tests/integration/scenarios/low_cpu_notdump.sh
tests/integration/scenarios/low_cpu_trigger_cpu_memory.sh
tests/integration/scenarios/ondemand.sh

This change allows to specify a custom output directory and file name for the generated core dump files. So far, the dumps were always placed in the current directory and had the format `<process name>_<type>_<date>.<pid>`.
Now, using the `-o` command line option, there are the following options:
- if you pass an existing directory or a path that ends in a slash, we use the passed path as the target directory while the name stays in the default format.
- otherwise, the passed string is split up into `directory` and `basename` components, and the core dumps are created in `<directory>` with the name `<basename>_<counter>.<pid>`.
The new test cases check if using a non-existing directory fails and if using a custom file name produces a core dump file in the temp directory created for the …

Allow custom path/file name for core dumps

---

include/ProcDumpConfiguration.h
src/ProcDumpConfiguration.c

Increased MAX_TRIGGERS to 10.  There's currently 5 triggers.  Added error checking in case more than 10 triggers are made inadvertently.  Also used modulo operation to prevent array buffer overflow before we exit.

Fixed triggers array overflow

---

Makefile

Noticed missing build dependencies when attempted to enable parallelism
on NixOS procdump package. There build failed as:
$ make -j16 -l16
rm -rf obj
gcc -c -g -o obj/CoreDumpWriter.o src/CoreDumpWriter.c -Wall -I ./include -pthread -std=gnu99
gcc -c -g -o obj/Events.o src/Events.c -Wall -I ./include -pthread -std=gnu99
gcc -c -g -o obj/Handle.o src/Handle.c -Wall -I ./include -pthread -std=gnu99
gcc -c -g -o obj/Logging.o src/Logging.c -Wall -I ./include -pthread -std=gnu99
rm -rf bin
gcc -c -g -o obj/ProcDumpConfiguration.o src/ProcDumpConfiguration.c -Wall -I ./include -pthread -std=gnu99
gcc -c -g -o obj/Procdump.o src/Procdump.c -Wall -I ./include -pthread -std=gnu99
gcc -c -g -o obj/Process.o src/Process.c -Wall -I ./include -pthread -std=gnu99
gcc -c -g -o obj/TriggerThreadProcs.o …

Makefile: add order-only build dependencies on directories

---

dist/procdump.spec.in

RPM 4.16 removed support for bare words in expressions (eg a == b needs to be a == b now). The change is backward compatible. More changes are in: https://rpm.org/wiki/Releases/4.16.0
This patch accommodates the above change and fixes more errors/warnings:
error: bare words are no longer supported, please use ...: redhat == debbuild
error: ^
error: /root/ProcDump-for-Linux/pkgbuild/SPECS/procdump.spec:6: bad %if condition: redhat == debbuild
make: *** [Makefile:91: rpm] Error 1

spec: fix bare words error with ProcDump 1.3 for el9

---

profiler/inc/ProcDumpProfiler.h
profiler/inc/profilerstring.h
profiler/src/ProcDumpProfiler.cpp
src/ProcDumpConfiguration.c
src/ProfilerHelpers.c
tests/integration/scenarios/dotnet_0WildcardExceptionDump1Thrown_dump.sh
tests/integration/scenarios/dotnet_1WildcardExceptionDump1Thrown_dump.sh
tests/integration/scenarios/dotnet_2WildcardExceptionDump2Thrown_dump.sh
tests/integration/scenarios/dotnet_wildcardexception_notdump.sh

Add wildcard filtering support when dump on exceptions #153

Add wildcard filtering support when dump on exceptions

---

Makefile

Without this dependency, `ld` fails with the following error when building with parallel tasks:
cannot find obj/ProcDumpProfiler.o: No such file or directory

Add missing dependency in Makefile

---

src/Monitor.c

This patchset proposes some fixes for:
- A double free of `monitoredProcessMap` in `MonitorProcesses()` due to an `auto_free` variable and several `free()` calls.
- Missing `va_end` call when `GetClientDataHelper()` finished early.
Most of these errors were reported by GCC 13 and they seem reasonable.

Fixing some leaks in src/Monitor.c code

---

src/DotnetHelpers.c
src/GenHelpers.c
src/Monitor.c

Hi,
This PR mainly addresses these "errors", listed below.
1. (`DotnetHelpers.c`) `fgets(...)` checks two times, the same buffer. Since it's a while loop and if the content is `NULL` it will be the same as checking it first in an if statement.
2. (`GenHelpers.c`) `GetUint16(...)` function implements the for loop in a way where `strlen(...)` function will get called on each iteration. So instead, a variable containing the pre-calculated length would be better.
3. (`GenHelpers.c`) `GetPath(...)` function uses a for loop, however, we're not using the index, so a while loop is better (will not require to have to compare on each iteration).
4. (`Monitor.c`) `threshold` was already checked whether its value is `NULL` or not. So the second check is pointless there.

Applied few changes

---

src/CoreDumpWriter.cpp
src/Monitor.cpp
src/ProcDumpConfiguration.cpp

This commit just cleans up a lot of unused variables across the code of ProcDump. For further validation, you can compile the code with `-Wall` and `-Werror` enabled.
Some of them change the logic of the code. IMHO, it includes some code cleanups as well.
Signed-off-by: Julio Faracco <jcfaracco@gmail.com>

Cleanup a lots of unused variables

---

sym/bcc_proc.cpp

I got some errors while I was compiling ProcDump 3.3. This PR just fix some of the compilation errors produced by Clang.
```
[ 46%] Building CXX object CMakeFiles/procdump.dir/sym/bcc_proc.cpp.o
/webhooks/ProcDump-for-Linux/sym/bcc_proc.cpp:479:16: error: variable length arrays in C++ are a Clang extension [-Werror,-Wvla-cxx-extension]
479 |   char search1[search_len + 1];
|                ^~~~~~~~~~~~~~
/webhooks/ProcDump-for-Linux/sym/bcc_proc.cpp:479:16: note: initializer of 'search_len' is not a constant expression
/webhooks/ProcDump-for-Linux/sym/bcc_proc.cpp:478:16: note: declared here
478 |   const size_t search_len = strlen(libname) + strlen("/lib.");
|                ^
/webhooks/ProcDump-for-Linux/sym/bcc_proc.cpp:480:16: error: variable length arrays in C++ are a Clang extension …
```

Fix clang compilation errors due to variable length arrays

---

src/Monitor.cpp

There are some variables in `CpuMonitoringThread()` function that are not being used. This is causing compilation issues by clang.
For further reference of the error, see the log below:
```[ 90%] Building CXX object CMakeFiles/procdump.dir/sym/bcc_elf.cpp.o
clang++  -I/root/rpmbuild/BUILD/procdump-3.4.0-build/ProcDump-for-Linux-3.4.0/include -I/root/rpmbuild/BUILD/procdump-3.4.0-build/ProcDump-for-Linux-3.4.0/redhat-linux-build -I/root/rpmbuild/BUILD/procdump-3.4.0-build/ProcDump-for-Linux-3.4.0/sym -I/root/rpmbuild/BUILD/procdump-3.4.0-build/ProcDump-for-Linux-3.4.0/ebpf -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS    -m64 -march=x86-64 -mtune=generic …
```

Monitor: removed useless variables

---

src/CoreDumpWriter.cpp

When gcore script doesn't output anything, there was a segmentation fault when accessing the output buffer.

fix segmentation fault when gcore script doesn't output anything

---

azure-pipelines.yml
profiler/src/ProcDumpProfiler.cpp
src/Monitor.cpp
src/ProfilerHelpers.cpp
tests/integration/helpers.sh
tests/integration/scenarios/dotnet_0ExceptionDump1Thrown_dump.sh
tests/integration/scenarios/dotnet_0WildcardExceptionDump1Thrown_dump.sh
tests/integration/scenarios/dotnet_1FilterExceptionMsgDump1Thrown_dump.sh
tests/integration/scenarios/dotnet_1WildcardExceptionDump1Thrown_dump.sh
tests/integration/scenarios/dotnet_1WildcardFilterExceptionMsgDump1Thrown_dump.sh
tests/integration/scenarios/dotnet_1_gc_gen_1_dump.sh
tests/integration/scenarios/dotnet_1_gc_threshold_1_dump.sh
tests/integration/scenarios/dotnet_1exceptionDump1Thrown_dump.sh
tests/integration/scenarios/dotnet_1exceptionDump2Thrown_dump.sh
tests/integration/scenarios/dotnet_2WildcardExceptionDump2Thrown_dump.sh
tests/integration/scenarios/dotnet_2exceptionDump2Thrown_dump.sh
tests/integration/scenarios/dotnet_3_gc_thresholds_3_dumps.sh
tests/integration/scenarios/dotnet_LOH_thresholds_3_dumps.sh
tests/integration/scenarios/dotnet_POH_thresholds_3_dumps.sh
tests/integration/scenarios/dotnet_gen_2_thresholds_3_dumps.sh

This pull request improves integration test reliability and observability for the ProcDump .NET profiler by adding explicit checks for profiler initialization and dump file creation. It also enhances logging in the profiler and related helper functions to aid debugging and test diagnostics.

Waiting for sockets and dumps to be written
